CREATE TABLE USERS (
   ID VARCHAR(37) NOT NULL,
   ROLE_ID VARCHAR(37) NOT NULL,
   GENDER_ID VARCHAR(37) NOT NULL,
   NAME varchar(255) NOT NULL,
   EMAIL VARCHAR(400) UNIQUE NOT NULL,
   ALTERNATIVE_EMAIL VARCHAR (400) UNIQUE NOT NULL,
   PASSWORD TEXT NOT NULL,
   PHONE_NO   VARCHAR(15),
   DOB TIMESTAMP,
   BIRTH_PLACE varchar(255) ,
   BIRTH_TIME TIMESTAMP(50) ,
   RAASI_ID varchar(37) NOT NULL,
   NAKSHATRAM_ID varchar(37) NOT NULL,
   `STATUS_ID` VARCHAR(37) NOT NULL default '000' ,
   CREATED_BY    VARCHAR(37) NOT NULL,
   CREATED_ON    TIMESTAMP NOT NULL,
   UPDATED_BY    VARCHAR(37),
   UPDATED_ON    TIMESTAMP,
   PRIMARY KEY (ID),
   FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
   FOREIGN KEY (GENDER_ID) REFERENCES GENDER(ID),
   FOREIGN KEY (RAASI_ID) REFERENCES RAASI(ID),
   FOREIGN KEY (NAKSHATRAM_ID) REFERENCES NAKSHATRAM(ID),
   FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID)
) ;





CREATE TABLE ADDRESS( 
	ID VARCHAR(37) NOT NULL,
	ADDRESS_LINE1 VARCHAR(500),
	ADDRESS_LINE2 VARCHAR(500),
	COUNTRY_ID VARCHAR(37) NOT NULL,
	STATE_ID VARCHAR(37),
	CITY_ID VARCHAR(37) NOT NULL,
	ZIPCODE VARCHAR(40) NOT NULL,
	USER_ID VARCHAR(37) NOT NULL,-- CUSTOMER
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (STATE_ID) REFERENCES STATES (ID),
	FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
	FOREIGN KEY (CITY_ID) REFERENCES CITY (ID),
	FOREIGN KEY (USER_ID)REFERENCES USERS(ID)
	
) ;


CREATE TABLE PUJA_ORDERS (
		  ID VARCHAR(37) NOT NULL,
		  USER_ID VARCHAR(37) NOT NULL,
		  PUJA_ID VARCHAR(37) NOT NULL,
		  AMOUNT double NOT NULL,
		  PAYED double NOT NULL,
		  `STATUS_ID` VARCHAR(37) NOT NULL default '000' ,
		  CREATED_BY    VARCHAR(37) NOT NULL,
		 CREATED_ON    TIMESTAMP NOT NULL,
		 UPDATED_BY    VARCHAR(37),
		 UPDATED_ON    TIMESTAMP,
		
       PRIMARY KEY (ID),  
       FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID),
	   FOREIGN KEY (USER_ID)REFERENCES USERS(ID),
	    FOREIGN KEY (PUJA_ID) REFERENCES PUJAS(ID)
);



CREATE TABLE PUJA_ORDERS_DETAILS (
  ID VARCHAR(37) NOT NULL,
  PUJA_ORDER_ID VARCHAR(37) NOT NULL,
  PUJA_SAMAGRI_ID varchar(37) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
   PRIMARY KEY (ID),
   FOREIGN KEY (PUJA_ORDER_ID) REFERENCES PUJA_ORDERS(ID),   
   FOREIGN KEY (PUJA_SAMAGRI_ID) REFERENCES PUJA_SAMAGRI(ID)
);




 CREATE TABLE CART_ORDERS (
	  ID VARCHAR(37) NOT NULL,
	  USER_ID VARCHAR(37) NOT NULL,
	  PUJA_ID VARCHAR(37) NOT NULL,
	  CREATED_BY    VARCHAR(37) NOT NULL,
	  CREATED_ON    TIMESTAMP NOT NULL,
	  UPDATED_BY    VARCHAR(37),
	  UPDATED_ON    TIMESTAMP,
      PRIMARY KEY (ID),  
	  FOREIGN KEY (USER_ID)REFERENCES USERS(ID),
	  FOREIGN KEY (PUJA_ID) REFERENCES PUJAS(ID)
);




CREATE TABLE CONTACT
 (
  ID VARCHAR(37) NOT NULL,
  NAME varchar(255) NOT NULL,
   EMAIL VARCHAR(400) UNIQUE NOT NULL,
    PHONE_NO   VARCHAR(15),
<<<<<<< HEAD
  SUBJECT TEXT NOT NULL,
  QUERY LONGTEXT NOT NULL,
  DATETIME TIMESTAMP NOT NULL,
=======
  subject text NOT NULL,
  query longtext NOT NULL,
  datetime TIMESTAMP NOT NULL,
>>>>>>> branch 'master' of https://github.com/VisogEmp/PASUPUKUMKUMA-API.git
  CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE TABLE USER_REQUESTS (
  ID VARCHAR(37) NOT NULL,
  REQUEST_ID varchar(255) NOT NULL,
  SUBJECT TEXT NOT NULL,
  MESSAGE LONGTEXT NOT NULL,
  CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (REQUEST_ID)REFERENCES USERS(ID)
) ;


CREATE TABLE COUPAN_VALUE
(  #REFERRED BY ,REFERRED TO
	ID VARCHAR(37) NOT NULL,
	COUPON_TYPE_ID  VARCHAR(37)UNIQUE NOT NULL,
	AMOUNT  DOUBLE,	
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID) ,
	FOREIGN KEY (COUPON_TYPE_ID) REFERENCES COUPON_TYPE(ID)	
	);

CREATE TABLE USER_REQUESTS_REPLY (
  ID VARCHAR(37) NOT NULL,
  REPLY_ID VARCHAR(37) NOT NULL,
  REQUEST_ID VARCHAR(37) NOT NULL,
 
  MESSAGE LONGTEXT NOT NULL,
  CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
  PRIMARY KEY (ID),  
  FOREIGN KEY (REPLY_ID)REFERENCES USERS(ID),
  FOREIGN KEY (REQUEST_ID)REFERENCES USER_REQUESTS(ID)
);

CREATE TABLE REFERAL_DETAILS (
ID VARCHAR(37) NOT NULL,
  REFERREDBY varchar(37) NOT NULL,
  REFERRED_TO_EMAIL VARCHAR(400) UNIQUE NOT NULL,
  COUPAN_CODE VARCHAR(400) NOT NULL,
  REFERAL_STATE_ID  VARCHAR(37) NOT NULL,#REFERRAL ACCEPTED/PENDING
  CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (REFERREDBY)REFERENCES USERS(ID)
) ;


CREATE TABLE COUPON_DETAILS (
  ID VARCHAR(37) NOT NULL,
  COUPON_TYPE_ID  VARCHAR(37) NOT NULL,
  USER_ID varchar(255) NOT NULL,
  COUPAN_CODE VARCHAR(400) NOT NULL,
  AMOUNT DOUBLE ,  
  CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID)REFERENCES USERS(ID),
  FOREIGN KEY (COUPON_TYPE_ID) REFERENCES COUPON_TYPE(ID)	
) ;


CREATE TABLE APP_SESSION (
  SESSION_ID VARCHAR(37) NOT NULL,
  USER_ID varchar(37) NOT NULL,
  LOGIN_DATE TIMESTAMP NOT NULL,
  LOGOUT_DATE TIMESTAMP NOT NULL,
  LAST_HIT_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (USER_ID)REFERENCES USERS(ID)
) ;
